class Estado_Envio ():
    GENERADO = 'GENERADO'
    CANCELADO = 'CANCELADO'
    EN_ESPERA = 'ESPERA'
    CONFIRMADO = 'CONFIRMADO'
    EN_VIAJE = 'VIAJE'
    NO_ENTREGADO = 'NO_ENTREGADO'
    ENTREGADO = 'ENTREGADO'