from sendit_app.models.Calificacion import Calificacion
from sendit_app.models.Categoria import Categoria
from sendit_app.models.Direccion import Direccion
from sendit_app.models.Empresa import Empresa
from sendit_app.models.Estado_Envio import Estado_Envio
from sendit_app.models.Estado_Paquete import Estado_Paquete
from sendit_app.models.Estado_Repartidor import Estado_Repartidor
from sendit_app.models.Persona import Persona
from sendit_app.models.Plan import Plan
from sendit_app.models.Rastreo import Rastreo
from sendit_app.models.Repartidor import Repartidor
from sendit_app.models.Sexo import Sexo
from sendit_app.models.Usuario import Usuario
from sendit_app.models.Vehiculo import Vehiculo
from sendit_app.models.Envio import Envio
from sendit_app.models.Paquete import Paquete