from sendit_app.models.Calificacion import Calificacion
from sendit_app.models.Categoria import Categoria
from sendit_app.models.Direccion import Direccion
from sendit_app.models.EstadoEnvio import EstadoEnvio
from sendit_app.models.EstadoPaquete import EstadoPaquete
from sendit_app.models.EstadoRepartidor import EstadoRepartidor
from sendit_app.models.Remitente import Remitente
from sendit_app.models.Plan import Plan
from sendit_app.models.Rastreo import Rastreo
from sendit_app.models.Repartidor import Repartidor
from sendit_app.models.Sexo import Sexo
from sendit_app.models.Vehiculo import Vehiculo
from sendit_app.models.Envio import Envio
from sendit_app.models.Paquete import Paquete
